### ISSUE TITLE
Feature request: Add haptic support for all buttons

### ISSUE THREAD

**Issue by benjgos** [iantrich/roku-card#22]
Hi,
I found how to add haptic feedback for the non-roku buttons (power, volume control...), but I can't find how to add it for the Roku buttons.
I tried the below which didn't produce haptic feedback (but did work as a home button), and couldn't find how to do it for the Apps.
```yml
            home:
              tap_action:
              haptic: medium
              action: call-service
              service: remote.send_command
              service_data:
                entity_id: remote.roku_bedroom
                command: home
```
Am I missing something or is there just no support for this yet?

Thanks!

**Comment by iantrich** [comment]
I'll add an option

**Comment by benjgos** [comment]
Excellent, thanks!

**Comment by iantrich** [comment]
I don't see myself doing this anytime soon; need to replace launchApp callservice with a call to handleClick with the formatted action wanted and a haptic parameter

https://github.com/custom-cards/roku-card/blob/master/src/roku-card.ts#L498

**Comment by iantrich** [comment]
Did a rewrite and while do so realized this was already possible, it was just an indentation error in your configuration
```yml
            home:
              tap_action:
                haptic: medium
                action: call-service
                service: remote.send_command
                service_data:
                  entity_id: remote.roku_bedroom
                  command: home
```
