### ISSUE TITLE
Trying to select different sources generates and error.

### ISSUE THREAD

**Issue by neuman1812** [iantrich/roku-card#33]
**Description of problem:**
Error when Selecting Source.  

**Config in Lovelace**
```
entity: media_player.livingroom
name: Living Room TV
theme: darkpurple
tv: true
type: 'custom:roku-card'
apps:
  - app: Live TV
    image: /local/antenna-icon.png
    tap_action:
      action: call-service
      service: media_player.select_source
      service_data:
        source: "Antenna\_TV"
  - app: Netflix
    image: /local/netflix.png
    tap_action:
      action: call-service
      service: media_player.select_source
      service_data:
        source: Netflix
  - app: Hulu
    image: /local/hulu.png
    tap_action:
      action: call-service
      service: media_player.select_source
      service_data:
        source: Hulu
  - app: PBS Kids
    image: /local/pbskids.png
    tap_action:
      action: call-service
      service: media_player.select_source
      service_data:
        source: PBS KIDS
```

**Javascript errors shown in the web inspector (if applicable):**

```
connection-mixin.ts:82 Uncaught (in promise) {code: "unknown_error", message: "must contain at least one of entity_id, area_id."}
```

**Additional information:**
