### ISSUE TITLE
Source Images not loading in iOS

### ISSUE THREAD

**Issue by jbeck22** [iantrich/roku-card#37]
I'm on HA version 0.108.0 -- updated earlier today.  iOS version 13.4.1 -- updated earlier today.

When I'm on a PC or MAC I see my source icons.  But from an iPad or iPhone in Safari or Chrome neither display the source icons.

**Comment by G3GhostTech** [comment]
Having same issue. Only shows place holders

**Comment by tescher** [comment]
Same here, on web version - Firefox 75 on Win 10

**Comment by haux03** [comment]
Loaded up today and images not loading for me either. Home Assistant 0.108.3, using Chrome Version 80.0.3987.163 on Windows 10. Everything else working great. Thanks.

**Comment by maxxxxpower** [comment]
Ditto. Could it have to do with the change from /community_plugin/ to /hacsfiles/ in terms of file structure?

I have tried changing the icon path to a few different ones, with webp copies of the icons in each, but haven't been able to get them to load.

**Comment by maxxxxpower** [comment]
Working again for me. I had updated the image paths to /local/roku-card/image.webp, but no go, despite the files existing at hacsfiles/roku-card/image.webp.

I recreated /community_plugin/roku-card/image.webp. Pointed the roku-card icons to those files and it's working again. Not sure why it did not work when trying both /local/ and /hacsfiles/ instead of /community_plugin/.

**Comment by Geezus42** [comment]
I cannot get them to load on Firefox 77. I have tried changing the path using the full path and the suggestions above.

**Comment by Geezus42** [comment]
This is what I get from:

cards:
  - entity: media_player.holocron
    type: media-control
  - apps:
      - app: Netflix
        hold_action:
          action: call-service
          service: media_player.select_source
          service_data:
            entity_id: media_player.holocron
            source: YouTube
        image: /local/netflix.png
      - app: Disney Plus
        hold_action:
          action: call-service
          service: media_player.select_source
          service_data:
            entity_id: media_player.holocron
            source: Hulu
        image: /local/disney.png
    entity: media_player.holocron
    tv: true
    type: 'custom:roku-card'
    volume_down:
      double_tap_action:
        action: call-service
        service: remote.send_command
        service_data:
          command: play
          entity_id: remote.holocron
    volume_up:
      double_tap_action:
        action: call-service
        service: remote.send_command
        service_data:
          command: play
          entity_id: remote.holocron
type: vertical-stack

image

**Comment by iantrich** [comment]
Still not able to replicate this, but a potential workaround that I added is the ability to use icons for apps instead: https://github.com/iantrich/roku-card/releases/tag/1.1.4

**Comment by Geezus42** [comment]
Using icons does not work for me either. I know there's no mdi icon for Disney but there is for Netflix.

```
apps:
  - app: Netflix
    hold_action:
      action: call-service
      service: media_player.select_source
      service_data:
        entity_id: media_player.holocron
        source: YouTube
    icon: 'mdi:Netflix'
  - app: Disney Plus
    hold_action:
      action: call-service
      service: media_player.select_source
      service_data:
        entity_id: media_player.holocron
        source: Hulu
    icon: 'mdi:Disney'
entity: media_player.holocron
select:
  hold_action:
    action: call-service
    service: media_player.select_source
    service_data:
      entity_id: media_player.holocron
      source: Xbox
tv: true
type: 'custom:roku-card'
volume_down:
  double_tap_action:
    action: call-service
    service: remote.send_command
    service_data:
      command: play
      entity_id: remote.holocron
volume_up:
  double_tap_action:
    action: call-service
    service: remote.send_command
    service_data:
      command: play
      entity_id: remote.holocron
```
![image](https://user-images.githubusercontent.com/10358134/87173013-becbc980-c29a-11ea-82bd-d846463deefe.png)
