### ISSUE TITLE
Buttons Stopped Working

### ISSUE THREAD

**Issue by dadeboni** [iantrich/roku-card#39]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
1.0.9
**Last working release (if known):**
1.0.8
**Browser and Operating System:**

**Description of problem:**

Config:
```
apps:
  - app: YouTube TV
    image: /local/youtube_tv.jpg
  - app: Netflix
    image: /local/netflix.png
  - app: YouTube
    image: /local/youtube.png
entity:
  - media_player.roku_yg009s871403
type: 'custom:roku-card'
```

None of the buttons on the card are working. When a button is pressed I receive 
Logger: frontend.js.latest.202004072
Source: components/system_log/__init__.py:209
First occurred: 10:04:23 AM (9 occurrences)
Last logged: 10:22:10 AM

http://mylocalip:8123/hacsfiles/roku-card/roku-card.js:282:253 Uncaught TypeError: this._config.entity.split is not a function
**Javascript errors shown in the web inspector (if applicable):**

```
Uncaught TypeError: this._config.entity.split is not a function
    at HTMLElement._handleAction (roku-card.js:282)
    at T.handleEvent (roku-card.js:68)
    at HTMLImageElement.T.__boundHandleEvent (roku-card.js:68)
    at Nt (roku-card.js:186)
    at HTMLImageElement.i (roku-card.js:186)
```

**Additional information:**
