### ISSUE TITLE
Roku buttons do not show up, they are invisible

### ISSUE THREAD

**Issue by nicxvan** [iantrich/roku-card#44]
- [1.1.3 ] I updated to the latest version available
- [ * ] I cleared the cache of my browser

**Release with the issue:**
1.1.3
Docker on a nuc

I'm on firefox Macos

**Description of problem:**
The card buttons are the same color as the background. I tried both with custom card styles as well as the default (I removed the style stanza in the configuration below.

**Javascript errors shown in the web inspector (if applicable):**

```
No errors
```

Card yaml
```
apps:
  - app: Netflix
    image: /local/netflix-icon.png
  - app: Plex - Stream Free Movies & TV
    image: /local/Plex-icon.png
  - app: Prime Video
    image: /local/Amazon-icon.png
  - app: Roku Media Player
    image: /local/Media-windows-media-player-icon.png
entity: media_player.bedroom_roku
name: Bedroom roku
remote: remote.bedroom
style: |
  ha-card {
    --ha-card-background: black;
  }
  .card-header {
    color: white;
  }
  paper-icon-button {
    color: grey;
  }
  .card-content {
    padding: 0
  }
theme: darkpurple
tv: false
type: 'custom:roku-card'

```

**Comment by nicxvan** [comment]
https://i.imgur.com/CcKOxeO.jpg

**Comment by nicxvan** [comment]
Reinstalling all of the front end plugins again from HACS seems to have fixed it.

**Comment by nicxvan** [comment]
I spoke too soon. Reinstalling only fixes it for a couple minutes, refreshing a couple of times breaks the remote again.

It still works, you just can't see the buttons.

**Comment by nicxvan** [comment]
I think it might be something to do with caching, if I hard refresh it, the buttons show up until I refresh again.

**Comment by rfeagley** [comment]
I'm seeing the same issue with hidden buttons.  They never show for me though regardless the state of my cache

**Comment by Geezus42** [comment]
I have the opposite issue.

This is what I get from:

```
cards:
  - entity: media_player.holocron
    type: media-control
  - apps:
      - app: Netflix
        hold_action:
          action: call-service
          service: media_player.select_source
          service_data:
            entity_id: media_player.holocron
            source: YouTube
        image: /local/netflix.png
      - app: Disney Plus
        hold_action:
          action: call-service
          service: media_player.select_source
          service_data:
            entity_id: media_player.holocron
            source: Hulu
        image: /local/disney.png
    entity: media_player.holocron
    tv: true
    type: 'custom:roku-card'
    volume_down:
      double_tap_action:
        action: call-service
        service: remote.send_command
        service_data:
          command: play
          entity_id: remote.holocron
    volume_up:
      double_tap_action:
        action: call-service
        service: remote.send_command
        service_data:
          command: play
          entity_id: remote.holocron
type: vertical-stack
```

![image](https://user-images.githubusercontent.com/10358134/86404544-721e3800-bc75-11ea-9aa8-75c74034301e.png)
