### ISSUE TITLE
Roku App Buttons dont work

### ISSUE THREAD

**Issue by andrewchumchal** [iantrich/roku-card#45]
**Checklist:**

- [X ] I updated to the latest version available
- [X ] I cleared the cache of my browser

**Release with the issue:**
1.1.3

**Last working release (if known):**

**Browser and Operating System:**
Firefox Windows 10 Pro

**Description of problem:**

When i tap on the one of the apps buttons i get the error messgaes in the screen shoot
[https://i.imgur.com/n444oDj.png](https://i.imgur.com/n444oDj.png)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

My Remote Config
```
entity: remote.office_roku_office
tv: false
type: 'custom:roku-card'
apps:
  - app: Plex - Stream Free Movies & TV
       image: '/local/plex.webp'
  - app: Netflix
       image: '/local/netflix.webp'
  - app: Hulu
       image: '/local/hulu.webp'
  - app: Prime Video
       image: '/local/prime.webp'
```
