### ISSUE TITLE
Hiding Buttons Only Hides Icon

### ISSUE THREAD

**Issue by stmrocket** [iantrich/roku-card#47]
**Checklist:**

- [ X] I updated to the latest version available
- [X ] I cleared the cache of my browser

**Release with the issue:** 1.1.4

**Last working release (if known):** Unknown

**Browser and Operating System:** Chrome 83.0.4103.116 / Windows 10

**Description of problem:**
I am not 100% sure if this is a bug report or a feature request.  When the show option for a button on the remote is set to false, the icon disappears but the button is still present.  Both the blank space remains and mousing over the button location will still show the presence of the button and allow it to be clicked.  

For example,
```
type: 'custom:roku-card'
entity: media_player.roku_living_room
apps:
  show: false
down:
  show: false
left:
  show: false
right:
  show: false
select:
  show: false
up:
  show: false  
```
Returns:
![roku_card](https://user-images.githubusercontent.com/19308297/86987752-67274400-c15c-11ea-96c9-ea13a76fa357.PNG)

**Javascript errors shown in the web inspector (if applicable):**

**Additional information:**
