### ISSUE TITLE
Button images not showing on v1.2.3

### ISSUE THREAD

**Issue by dpomnean** [iantrich/roku-card#73]
**Checklist:**

- [ yes ] I updated to the latest version available
- [ yes ] I cleared the cache of my browser

**Release with the issue:**
v1.2.3
**Last working release (if known):**
v1.2.2
**Browser and Operating System:**
Windows. Chrome. Also happens on firefox and the mobile app

**Description of problem:**
The card will show the background of the buttons if you hover over them, but will not show the button image. Occurs on desktop, mobile in browser and the mobile app.

![image](https://user-images.githubusercontent.com/17032114/141597312-b21de2e1-67db-4bf5-8b0b-02cac0aa62e8.png)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

Card config

```
type: conditional
conditions:
  - entity: input_select.roku
    state: living room
card:
  type: custom:roku-card
  entity: media_player.roku_tv
  tv: true
  apps:
    - icon: mdi:netflix
      app: Netflix
    - icon: mdi:plex
      app: Plex - Free Movies & TV
    - icon: mdi:hulu
      app: Hulu
    - icon: mdi:youtube
      app: YouTube

```
